planning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('sales/', include('sales.urls'))

]

sales/urls.py
from django.urls import path
from . import views as sales_views
from .models import *

app_name = 'sales'
urlpatterns = [
    path('customer/new/', sales_views.CustomerCreateView.as_view(), name="customer-create"),
    path('customer/list/', sales_views.CustomerListView.as_view(), name="customer-list"),
    path('customer/update/<int:pk>/', sales_views.CustomerUpdateView.as_view(), name="customer-update"),
    path('customer/detail/<int:pk>/', sales_views.CustomerDetailView.as_view(), name="customer-detail"),
    path('customer/delete/<int:pk>/', sales_views.CustomerDeleteView.as_view(), name="customer-delete"),
    path('plan/new/', sales_views.create_sales_plan_redirect, name='sales-plan-create-form'),
    path('plan/new/<str:pk>/<int:year>/<int:month>/<int:day>/', sales_views.create_sales_plan, name="sales-plan"),
    path('plan/list/', sales_views.SalesPlanListView.as_view(), name="sales-plan-list"),
    path('plan/detail/<int:pk>', sales_views.SalesPlanDetailView.as_view(), name="sales-plan-detail"),
    path('plan/update/<int:pk>/', sales_views.SalesPlanUpdateView.as_view(), name="sales-plan-update"),
    path('plan/delete/<int:pk>/', sales_views.SalesPlanDeleteView.as_view(), name="sales-plan-delete"),

]

sales/models.py
from django.db import models
from products.models import Product
from django.urls import reverse


# Create your models here.

class SalesChannel(models.Model):
    code = models.CharField(max_length=5, primary_key=True, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Customer(models.Model):
    code = models.CharField(max_length=6, primary_key=True, unique=True, help_text="Customer Code 6 digits")
    name = models.CharField(max_length=100, help_text="Customer Name")
    belongs_to_sales_channel = models.ForeignKey(SalesChannel, on_delete=models.RESTRICT, help_text="Select sales channel")
    portfolio = models.ManyToManyField(Product, help_text="Hold Shift to select multiple products or hold Control to select individual products")
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sales:customer-detail', kwargs={'pk': self.pk})
    


class SalesRecords(models.Model):
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    date = models.DateField()
    quantity = models.FloatField()
    customer = models.ForeignKey(Customer, on_delete=models.RESTRICT)

    class Meta:
        verbose_name_plural = "Sales Records"

    def __str__(self):
        sales_records_info = str(self.customer) + ' - ' + str(self.date) + ' - ' + str(self.product)
        return str(sales_records_info)
    
   
  
    
class SalesPlan(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.RESTRICT)
    date = models.DateField(null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    quantity = models.FloatField(default=0)

    class Meta:
        unique_together = [['customer', 'date', 'product']]
        # constraints = [
        #     models.UniqueConstraint(fields=['customer', 'date', 'product'], name='unique_salesplan')
        # ]
    
    def __str__(self):
        sales_plan_info = str(self.customer) + ' - ' + str(self.date) + ' - ' + str(self.product)
        return str(sales_plan_info)

    def get_creation_url(self):
        kwargs={
            'pk': str(self.customer.code),
            'year': str(self.date.year),
            'month': str(self.date.month),
            'day': str(self.date.day)
        }
        return reverse('sales:sales-plan', kwargs=kwargs)

    def get_absolute_url(self):
        return reverse('sales:sales-plan-detail', kwargs={'pk': self.pk})

sales/forms.py
from django import forms
from django.db.models import fields
from .models import *
from django.forms import modelformset_factory, widgets
from django.contrib.humanize.templatetags.humanize import intcomma


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            
        }


class SalesPlanForm(forms.ModelForm):
    # product = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    class Meta:
        model = SalesPlan
        fields = '__all__'
        widgets = {
            'customer': forms.HiddenInput(),
            'date': forms.HiddenInput(),
            
        }

SalesPlanFormSet = modelformset_factory(SalesPlan, form=SalesPlanForm, extra=0)
    
class SalesPlanFrameForm(forms.ModelForm):
    date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = SalesPlan
        fields = ('customer', 'date',)

sales/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.forms import formset_factory, formsets, modelformset_factory
from django.urls.base import reverse_lazy
from django.views.generic.edit import DeleteView
from .models import *
from .forms import *
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView
from django.db.models import Sum, F
import pandas as pd


# Customer Views #
#########################################################


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    
    # def get_success_url(self):
    #     return reverse('sales:customer-detail', kwargs={'pk': self.object.pk})


class CustomerDetailView(DetailView):
    model = Customer
    

class CustomerListView(ListView):
    model = Customer
    ordering = ['belongs_to_sales_channel', 'code',]


class CustomerUpdateView(UpdateView):
    model = Customer
    fields = '__all__'
    success_url = reverse_lazy('sales:customer-list')
    
    
class CustomerDeleteView(DeleteView):
    model = Customer
    success_url = reverse_lazy('sales:customer-list')


# Sales Plan Views #
#########################################################

def create_sales_plan_redirect(request, pk=None, year=None, month=None, day=None):
    form = SalesPlanFrameForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        return redirect(obj.get_creation_url())
    context = {
        'form': form
    }
    return render(request, 'sales/salesplan_form.html', context)

def create_sales_plan(request, pk, year, month, day):
    customer = get_object_or_404(Customer, code=pk)
    portfolio = customer.portfolio.all()
    date = str(str(year)+'-'+str(month)+'-'+str(day))
    initial = []
    for item in portfolio:
        initial.append({'customer':customer, 'product':item, 'quantity':0, 'date':date})
    SalesPlanFormSet = formset_factory(SalesPlanForm, extra=0)
    formset = SalesPlanFormSet(initial=initial)
    if request.method == "POST":
        formset = SalesPlanFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                quantity = form.cleaned_data['quantity']
                
                if quantity > 0 :
                    form.save()                   
            return redirect('/')
    context = {
        'formset': formset,
        'customer': customer,
        'date': date,
    }
    return render(request, 'sales/salesplan-create.html', context)


class SalesPlanListView(ListView):
    """
    Should consider changing to function based view to make it more palatable and functional:
    for example, introduce filter for customers, dates and display plans below in the table.
    Also, nice thing would be to be able to delete all plans for customer and date selected.
    """
    model = SalesPlan
    ordering = ['date', 'customer', 'product',]


class SalesPlanDetailView(DetailView):
    model = SalesPlan
    

class SalesPlanUpdateView(UpdateView):
    model = SalesPlan
    fields = '__all__'
    success_url = reverse_lazy('sales:sales-plan-list')


class SalesPlanDeleteView(DeleteView):
    model = SalesPlan
    success_url = reverse_lazy('sales:sales-plan-list')

sales/templates/sales/customer_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        <div>
            <h2>Are you sure you want to delete {{ object }}?</h2>
        </div>
        <div>
            <button class="btn btn-danger" type="submit" >Yes</button>
            <a class="btn btn-warning" href="{% url 'sales:customer-list' %}">No</a>
        </div>
    </form>
</div>

{% endblock content %}

sales/templates/sales/customer_detail.html
{{object.code}} {{object.name}}

sales/templates/sales/customer_form.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save">
    
    </form>
</div>

{% endblock content %}

sales/templates/sales/customer_list.html
{% extends 'dashboard/base.html' %}

{% block content %}
<table class="table" style="text-align: center;">
    {% csrf_token %}
    <thead>
      <tr >
        <th>Sales Channel</th>        
        <th>Code</th>        
        <th>Name</th>        
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>        
      </tr>
    </thead>
    <tbody>
        {% for customer in object_list %}
            <tr>
              <th>{{customer.belongs_to_sales_channel}}</th>
              <th>{{customer.code}}</th>
              <td>{{customer.name}}</td>
                <td><a href="{% url 'sales:customer-detail' customer.code %}">Details</a></td>
                <td><a href="{% url 'sales:customer-update' customer.code %}">Edit</a></td>
                <td><a href="{% url 'sales:customer-delete' customer.code %}">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>

  {% endblock content %}

sales/templates/sales/salesplan-create.html
{% extends 'dashboard/base.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    
    {{formset.management_form}}
    <h1>Customer: {{customer}}</h1>
    <hr>
    <h1>Date: {{date}}</h1>
    <table class="table-sm">
    
        <thead>
            <th></th>
            <th></th>
            <th>Product</th>
            <th>Quantity</th>
        </thead>
        <tbody>
            {% for form in formset %}
                <tr>
                    {% for field in form %}
                        <td>{{field}}</td>
                    {% endfor %}  
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <input type="submit", value="Submit">
</form>
{% endblock content %}

sales/templates/sales/salesplan_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        <div>
            <h2>Are you sure you want to delete {{ object }}?</h2>
        </div>
        <div>
            <button class="btn btn-danger" type="submit" >Yes</button>
            <a class="btn btn-warning" href="{% url 'sales:sales-plan-list' %}">No</a>
        </div>
    </form>
</div>

{% endblock content %}

sales/templates/sales/salesplan_detail.html
{{object}} 

sales/templates/sales/salesplan_form.html
{{formset}}

sales/templates/sales/salesplan_list.html
{% extends 'dashboard/base.html' %}

{% block content %}
<table class="table" style="text-align: center;">
    {% csrf_token %}
    <thead>
      <tr >
        <th>Customer</th>
        <th>Product</th>
        <th>Date</th>
        <th>Quantity</th>
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>        
      </tr>
    </thead>
    <tbody>
        {% for salesplan in object_list %}
            <tr>
              <th>{{salesplan.customer}}</th>
              <th>{{salesplan.product}}</th>
              <td>{{salesplan.date}}</td>
              <td>{{salesplan.quantity}}</td>
                <td><a href="{% url 'sales:sales-plan-detail' salesplan.pk %}">Details</a></td>
                <td><a href="{% url 'sales:sales-plan-update' salesplan.pk %}">Edit</a></td>
                <td><a href="{% url 'sales:sales-plan-delete' salesplan.pk %}">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>

  {% endblock content %}