dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.home_view, name='home'),
    

]

planning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('sales/', include('sales.urls'))

]

products/urls.py
from django.urls import path
from . import views as product_views
from django.contrib.auth.views import LogoutView

app_name = 'products'
urlpatterns = [
    path('create/', product_views.ProductCreateView.as_view(), name='create-product'),
    path('list/', product_views.ProductListView.as_view(), name='list-product'),
    path('update/<int:pk>/', product_views.ProductUpdateView.as_view(), name='update-product'),
    path('delete/<int:pk>/', product_views.ProductDeleteView.as_view(), name='delete-product'),
    path('detail/<int:pk>/', product_views.ProductDetailView.as_view(), name='detail-product'),
    
]

sales/urls.py
from django.urls import path
from . import views as sales_views
from .models import *

app_name = 'sales'
urlpatterns = [
    path('customer/new/', sales_views.CustomerCreateView.as_view(), name="customer-create"),
    path('customer/list/', sales_views.CustomerListView.as_view(), name="customer-list"),
    path('customer/update/<int:pk>/', sales_views.CustomerUpdateView.as_view(), name="customer-update"),
    path('customer/detail/<int:pk>/', sales_views.CustomerDetailView.as_view(), name="customer-detail"),
    path('customer/delete/<int:pk>/', sales_views.CustomerDeleteView.as_view(), name="customer-delete"),
    path('plan/new/', sales_views.create_sales_plan_redirect, name='sales-plan-create-form'),
    path('plan/new/<str:pk>/<int:year>/<int:month>/<int:day>/', sales_views.create_sales_plan, name="sales-plan"),
    path('plan/list/', sales_views.SalesPlanListView.as_view(), name="sales-plan-list"),
    path('plan/detail/<int:pk>', sales_views.SalesPlanDetailView.as_view(), name="sales-plan-detail"),
    path('plan/update/<int:pk>/', sales_views.SalesPlanUpdateView.as_view(), name="sales-plan-update"),
    path('plan/delete/<int:pk>/', sales_views.SalesPlanDeleteView.as_view(), name="sales-plan-delete"),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from sales.models import *
from products.models import *
from sales.forms import *


# Create your views here.
def home_view(request):
    sales_channels = SalesChannel.objects.all()
    customers = Customer.objects.all()
    products = Product.objects.all()
    context = {
        'sales_channels': sales_channels,
        'products': products,
        'customers': customers,
    }
    return render(request, 'dashboard/home.html', context)

dashboard/templates/dashboard/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  </head>
  <body>
    {% include 'dashboard/navbar.html' %}
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
   
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div>
    <h1>sales channels</h1>
    <table class="table">
        <thead>
            <th>
                channel code
            </th>       
            <th>
                channel name
            </th>       
        </thead>
        <tbody>
            {% for channel in sales_channels %}
            <tr>
                <td>
                    {{channel.code}}
                </td>
                <td>
                    {{channel.name}}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
<div>
    <h1>customers</h1>
    <table class="table">
        <thead>
            <th>
                customer code
            </th>       
            <th>
                customer name
            </th>       
            <th>
                sales channel member
            </th>       
        </thead>
        <tbody>
            {% for customer in customers %}
            <tr>
                <td>
                    <a href="{% url 'sales:customer-detail' pk=customer.code %}">{{customer.code}}</a>
                </td>
                <td>
                    {{customer.name}}
                </td>
                <td>
                    {{customer.belongs_to_sales_channel}}
                </td>
                <td>
                    {{customer.portfolio.count}}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <h1>Products</h1>
    <table class="table">
        <thead>
            <th>
                product group
            </th>       
            <th>
                product subgroup
            </th>       
            <th>
                item code
            </th>       
            <th>
                item name
            </th>       
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>
                    {{product.product_group}}
                </td>
                <td>
                    {{product.product_subgroup}}
                </td>
                <td>
                    <a href="{% url 'products:detail-product' pk=product.pk %}">{{product.code}}</a>
                </td>
                <td>
                    {{product.name}}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content%}

dashboard/templates/dashboard/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Terran Corp. Planning</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'dashboard:home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'products:create-product' %}">Create New Product</a></li>
            <li><a class="dropdown-item" href="{% url 'products:list-product' %}">All Products</a></li> 
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sales
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'sales:sales-plan-create-form' %}">Create Sales Plan</a></li>
            <li><a class="dropdown-item" href="{% url 'sales:sales-plan-list' %}">List all plans</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sales Records</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>