planning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('sales/', include('sales.urls'))

]

products/urls.py
from django.urls import path
from . import views as product_views
from django.contrib.auth.views import LogoutView

app_name = 'products'
urlpatterns = [
    path('create/', product_views.ProductCreateView.as_view(), name='create-product'),
    path('list/', product_views.ProductListView.as_view(), name='list-product'),
    path('update/<int:pk>/', product_views.ProductUpdateView.as_view(), name='update-product'),
    path('delete/<int:pk>/', product_views.ProductDeleteView.as_view(), name='delete-product'),
    path('detail/<int:pk>/', product_views.ProductDetailView.as_view(), name='detail-product'),
    
]

sales/urls.py
from django.urls import path
from . import views as sales_views
from .models import *

app_name = 'sales'
urlpatterns = [
    path('customer/new/', sales_views.CustomerCreateView.as_view(), name="customer-create"),
    path('customer/list/', sales_views.CustomerListView.as_view(), name="customer-list"),
    path('customer/update/<int:pk>/', sales_views.CustomerUpdateView.as_view(), name="customer-update"),
    path('customer/detail/<int:pk>/', sales_views.CustomerDetailView.as_view(), name="customer-detail"),
    path('customer/delete/<int:pk>/', sales_views.CustomerDeleteView.as_view(), name="customer-delete"),
    path('plan/new/', sales_views.create_sales_plan_redirect, name='sales-plan-create-form'),
    path('plan/new/<str:pk>/<int:year>/<int:month>/<int:day>/', sales_views.create_sales_plan, name="sales-plan"),
    path('plan/list/', sales_views.SalesPlanListView.as_view(), name="sales-plan-list"),
    path('plan/detail/<int:pk>', sales_views.SalesPlanDetailView.as_view(), name="sales-plan-detail"),
    path('plan/update/<int:pk>/', sales_views.SalesPlanUpdateView.as_view(), name="sales-plan-update"),
    path('plan/delete/<int:pk>/', sales_views.SalesPlanDeleteView.as_view(), name="sales-plan-delete"),

]

products/models.py
from django.db import models

# Create your models here.


class ProductGroup(models.Model):
    product_group = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.product_group


class ProductSubGroup(models.Model):
    product_group = models.ForeignKey(ProductGroup, on_delete=models.RESTRICT)
    product_subgroup = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.product_subgroup


class Product(models.Model):
    product_group = models.ForeignKey(ProductGroup, on_delete=models.RESTRICT)
    product_subgroup = models.ForeignKey(ProductSubGroup, on_delete=models.RESTRICT)
    code = models.CharField(max_length=5, unique=True)
    name = models.CharField(max_length=100)
    unit_of_measure = models.CharField(max_length=10)
    weight = models.DecimalField(max_digits=5, decimal_places=3)
    weight_text = models.CharField(max_length=10)

    def __str__(self):
        product_info = str(self.code) + ' - ' + str(self.name)
        return str(product_info)

products/views.py
from django.db.models import fields
from django.shortcuts import render
from django.views.generic.detail import DetailView
from products.models import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

# Create your views here.
class ProductCreateView(CreateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('products:list-product')

class ProductListView(ListView):
    model = Product
    ordering = ['product_group', 'code', 'weight']
    
class ProductUpdateView(UpdateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('products:list-product')

class ProductDetailView(DetailView):
    model = Product
    
    

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('products:list-product')

products/templates/products/product_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        <div>
            <h2>Are you sure you want to delete {{ object }}?</h2>
        </div>
        <div>
            <button class="btn btn-danger" type="submit" >Yes</button>
            <a class="btn btn-warning" href="{% url 'products:list-product' %}">No</a>
        </div>
    </form>
</div>

{% endblock content %}

products/templates/products/product_detail.html
{{object.code}} {{object.name}}

products/templates/products/product_form.html
<form action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">

</form>

products/templates/products/product_list.html
{% extends 'dashboard/base.html' %}

{% block content %}
<table class="table" style="text-align: center;">
    {% csrf_token %}
    <thead>
      <tr >
        <th>Product Group</th>
        <th>Code</th>        
        <th>Name</th>        
        <th>UoM</th>
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>        
      </tr>
    </thead>
    <tbody>
        {% for product in object_list %}
            <tr>
                <th>{{product.product_group}}</th>
                <th>{{product.code}}</th>
                <td>{{product.name}}</td>
                <td>{{product.unit_of_measure}}</td>
                <td><a href="{% url 'products:detail-product' product.id %}">Details</a></td>
                <td><a href="{% url 'products:update-product' product.id %}">Edit</a></td>
                <td><a href="{% url 'products:delete-product' product.id %}">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>

  {% endblock content %}